baseURL: https://clement-w.github.io/

languageCode: en-us
title: "Clément Weinreich's Website"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
    en:
        languageName: English
        weight: 1

# Control TOC depth
markup:
    tableOfContents:
        startLevel: 2
        endLevel: 6
        ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
    # GitHub repo URL of your site
    gitRepo: https://github.com/Clement-W/clement-w.github.io

    background: "images/site/b.jpg"

    # The inverted logo will be used in the initial transparent navbar and
    # the main logo will be used in the non-transparent navbar.
    logo:
        main: images/site/favicon2.png
        inverted: images/site/favicon2.png
        favicon: images/site/favicon2.png

    darkMode:
        provider: darkreader
        enable: true
        default: light

    # specify whether you want to write some blog posts or not
    enableBlogPost: true

    # specify whether you want to show Table of Contents in reading page
    enableTOC: true

    # Provide newsletter configuration. This feature hasn't been implemented yet.
    # Currently, you can just hide it from the footer.
    newsletter:
        enable: false

    analytics:
        enabled: true
        # Google Analytics
        google:
        id: TODO

    # Configure various features of this theme
    features:
        # Enable and configure portfolio
        portfolio:
            enable: true
        # Enable and configure blog posts
        blog:
            enable: true
